"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the
map we want to create.
"""
import sys
from pathlib import Path

# Insert the parent directory of the current file's directory into sys.path.
# This allows Python to locate modules that are one level above the current
# script, in this case spg_overlay.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1819, 1350)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    pass