"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (802, 602)

def dimensions():
    return (802,602)

def add_walls(playground):

    wall = NormalWall(pos_start=(-401, 300), pos_end=(401, 300))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(400, 301), pos_end=(400, -301))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-401, -300), pos_end=(401, -300))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-400, 301), pos_end=(-400, -301))
    playground.add(wall, wall.wall_coordinates)


def add_boxes(playground):

    box = NormalBox(up_left_point=(-225, 33), width=212, height=195)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(113, 222), width=184, height=137)
    playground.add(box, box.wall_coordinates)

