"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (806, 606)

def dimensions():
    return (806,606)

def add_walls(playground):

    wall = NormalWall(pos_start=(54, 227), pos_end=(354, 227))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(354, 225), pos_end=(354, -239))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-234, -236), pos_end=(355, -236))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-236, 76), pos_end=(-236, -236))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-86, 166), pos_end=(54, 166))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(48, 225), pos_end=(48, 160))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(45, 227), pos_end=(60, 227))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-235, 78), pos_end=(-97, 78))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-104, -84), pos_end=(-104, 71))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-101, 5), pos_end=(189, 5))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(185, 133), pos_end=(185, 10))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(43, 316), pos_end=(43, 229))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-239, -322), pos_end=(-239, -239))
    playground.add(wall, wall.wall_coordinates)


def add_boxes(playground):

    pass

