"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (806, 606)

def dimensions():
    return (806,606)

def add_walls(playground):

    wall = NormalWall(pos_start=(92, -35), pos_end=(92, 143))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(91, 86), pos_end=(210, 86))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(162, -18), pos_end=(162, 83))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(157, -111), pos_end=(280, -111))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(280, 44), pos_end=(280, -112))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(279, 45), pos_end=(279, 181))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(279, 51), pos_end=(279, 21))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(219, 181), pos_end=(282, 181))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(208, 18), pos_end=(277, 18))
    playground.add(wall, wall.wall_coordinates)


def add_boxes(playground):

    pass

