"""
This file was generated by the tool 'map_editor_gui.py' in the directory map_editor.
This tool permits to create this kind of file by using a graphical interface.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox

# Dimension of the map : (1576, 1011)

def dimensions():
    return (1576,1011)

def add_walls(playground):

    wall = NormalWall(pos_start=(-788, 504), pos_end=(788, 504))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(787, 505), pos_end=(787, -505))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-788, -504), pos_end=(788, -504))
    playground.add(wall, wall.wall_coordinates)

    wall = NormalWall(pos_start=(-787, 505), pos_end=(-787, -505))
    playground.add(wall, wall.wall_coordinates)


def add_boxes(playground):

    box = NormalBox(up_left_point=(-488, -64), width=264, height=199)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(229, -46), width=285, height=215)
    playground.add(box, box.wall_coordinates)

    box = NormalBox(up_left_point=(226, 335), width=278, height=163)
    playground.add(box, box.wall_coordinates)

